#!/usr/bin/perl
#
# A script to receive build status from a Jenkins server
# and send out notification to Slack, and email addresses, if specified.

use JSON;
use CGI;
use Configure;
use strict;

my $cgi = new CGI;

$0 =~ s/.*\///;

my $DEBUG = 1;

use vars qw($key $val $success);
my $email = '';  # specify email addresses, if needed.

$val = $cgi->param('POSTDATA');

if(!$val)
{
    # silently quit after putting an error note in the web log.
    print STDERR "no data for POSTDATA\n";
    exit(0);
}

$val = decode_json($val);

my $user = $val->{'build'}->{'log'};
$user =~ s/Notifying endpoint.*$//s;
$user =~ s/[[:^print:]]+$//s;
$user =~ s/.*[[:^print:]](\[0m)?//s;

$user =~ s/^Started by //;

my $name = $val->{'name'};
my $url = $val->{'build'}->{'full_url'};
my $phase = $val->{'build'}->{'phase'};
my $status = $val->{'build'}->{'status'};

my $data = '';
if($phase eq 'STARTED')
{
    $data .= $name . ' build started by ' . $user . "\n";
}
else
{
    if($status eq 'SUCCESS')
    {
        $data .= $name . " build completed successfully.\n";
        $success = 1;
    }
    else
    {
        $success = 0;
        $data .= $name . " build failed.\n";
    }
}

#you may change the command to send notice to other chatrooms other than Slack

$data .= $url . "console\n";

my $cmd = 'curl -X POST -H \'Content-type: application/json\' --data \'{"text":"' . $data . '"}\' https://hooks.slack.com/services/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';

system($cmd);

if($email)  # if email addresses are specified
{
    $cmd = "mail -s 'Jenkins Build Status' $email";
    open(MAIL, "|$cmd");
    print MAIL $data;
    close(MAIL);
}

exit(0);

